import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [


  // Admin Modules

  {
    path: '/admin/dashboard/dashboard2',
    title: 'MENUITEMS.DASHBOARD.LIST.DASHBOARD2',
    iconType: 'material-icons-two-tone',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:[],
    role: ['Admin'],
    permissions: [''],
    scholar_level: ['', 'University'],
    submenu: [],
    registrationPaid: '',
  },
  {
    path: '',
    title: 'MENUITEMS.ACCESS.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'settings',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:[],
    role: ['Admin'],
    permissions: [],
    scholar_level: ['', 'University'],
    registrationPaid: '',
    submenu: [
      {
        path: '/admin/privileges/all-privileges',
        title: 'MENUITEMS.ACCESS.LIST.PRIVILEGES',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:[],
        role: [''],
        scholar_level: [],
        permissions: [],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/admin/roles/all-roles',
        title: 'MENUITEMS.ACCESS.LIST.ROLES',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:[],
        role: [''],
        scholar_level: [],
        permissions: [],
        submenu: [],
        registrationPaid: '',
      }
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.CUSTOMERS.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'school',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:[],
    role: ['Admin'],
    permissions: [],
    scholar_level: ['', 'University'],
    registrationPaid: '',
    submenu: [
      {
        path: '/admin/fondateurs/all-fondateurs',
        title: 'MENUITEMS.FONDATEURS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:[],
        role: [''],
        scholar_level: [],
        permissions: [],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/admin/hotels/all-hotels',
        title: 'MENUITEMS.ESTABLISHMENTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:[],
        role: [''],
        scholar_level: [],
        permissions: [],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/admin/schools/all-schools',
        title: 'MENUITEMS.SCHOOLS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:[],
        role: [''],
        scholar_level: [],
        permissions: [],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/admin/departements/all-departements',
        title: 'MENUITEMS.SECTIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:[],
        role: [''],
        scholar_level: [],
        permissions: [],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
  
  {
    path: '/admin/packages/all-packages',
    title: 'MENUITEMS.PACKAGES.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'business',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:[],
    role: ['Admin'],
    permissions: [],
    scholar_level: ['', 'University'],
    submenu: [],
    registrationPaid: '',
  },
  
  {
    path: '/admin/invoices/all-invoices',
    title: 'MENUITEMS.INVOICES.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'money',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:[],
    role: ['Admin'],
    permissions: [],
    scholar_level: ['', 'University'],
    submenu: [],
    registrationPaid: '',
  },
  {
    path: '/admin/transactions/all-transactions',
    title: 'MENUITEMS.TRANSACTIONS.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'monetization_on',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:[],
    role: ['Admin'],
    permissions: [],
    scholar_level: ['', 'University'],
    submenu: [],
    registrationPaid: '',
  },

  
  
  // Founder Modules
  // Founder Modules
  // Founder Modules

  {
    path: '/founder/dashboard/main',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:['Founder', "Direction"],
    role: ['Founder', 'Principale', 'Rector', 'assistant'],
    permissions: ['stf-2','tea-2','std-2','eve-2','tac-2'],
    scholar_level: [''],
    submenu: [],
    registrationPaid: '',
  },

  // structure

  {
    path: '',
    title: 'MENUITEMS.ORGANISATION.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'person',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:['Founder', "Direction"],
    role: ['Founder', 'Principale', 'Rector', 'assistant'],
    scholar_level: [''],
    permissions: [''],
    registrationPaid: '',
    submenu: [
      {
        path: '/founder/organisations/all-staffs',
        title: 'MENUITEMS.ORGANISATION.LIST.STAFFS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'personnels administratifs administrative staff',
        badgeClass: '',
        typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        submenu: [],
        permissions: [''],
        registrationPaid: '',
      },
      {
        path: '/founder/organisations/all-customers',
        title: 'MENUITEMS.ORGANISATION.LIST.STUDENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'élèves eleves students',
        badgeClass: '',
        typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level:[''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/organisations/all-events',
        title: 'MENUITEMS.ORGANISATION.LIST.EVENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'événements evenements events',
        badgeClass: '',
        typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level:[''],
        submenu: [],
        registrationPaid: '',
        permissions: ['']
      },
      {
        path: '/founder/organisations/all-tasks',
        title: 'MENUITEMS.TASKS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'taches tâches tasks',
        badgeClass: '',
        typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        submenu: [],
        registrationPaid: '',
        permissions: ['']
      },
      {
        path: '/founder/hosting/all-feedbacks',
        title: 'MENUITEMS.FEEDBACKS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'levels niveaux',
        badgeClass: '',
        typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.HOSTING.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'layers',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:['Founder', "Direction"],
    role: ['Founder', 'Principale', 'Rector'],
    permissions: [''],
    scholar_level: [''],
    registrationPaid: '',
    submenu: [
      {
        path: '/founder/hosting/all-rooms',
        title: 'MENUITEMS.ROOMS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'filieres filières sectors streams',
        badgeClass: '',
        typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: ['University'],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/hosting/all-bookings',
        title: 'MENUITEMS.BOOKINGS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'levels niveaux',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/hosting/all-roomServices',
        title: 'MENUITEMS.ROOM-SERVICES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'levels niveaux',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },


  {
    path: '',
    title: 'MENUITEMS.RESTAURANT.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'layers',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:['Founder', "Direction"],
    role: ['Founder', 'Principale', 'Rector', 'assistant'],
    scholar_level: [''],
    permissions: [''],
    registrationPaid: '',
    submenu: [  
      {
        path: '/founder/restaurants/all-products',
        title: 'MENUITEMS.PRODUCTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/restaurants/all-orders',
        title: 'MENUITEMS.ORDERS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },  
      {
        path: '/founder/restaurants/all-productMovements',
        title: 'MENUITEMS.PRODUCTS-MOVEMENT.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.BARS.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'layers',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:['Founder', "Direction"],
    role: ['Founder', 'Principale', 'Rector', 'assistant'],
    scholar_level: [''],
    permissions: [''],
    registrationPaid: '',
    submenu: [  
      {
        path: '/founder/bars/all-products',
        title: 'MENUITEMS.PRODUCTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/bars/all-orders',
        title: 'MENUITEMS.ORDERS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },  
      {
        path: '/founder/bars/all-productMovements',
        title: 'MENUITEMS.PRODUCTS-MOVEMENT.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.WATERS.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'layers',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:['Founder', "Direction"],
    role: ['Founder', 'Principale', 'Rector', 'assistant'],
    scholar_level: [''],
    permissions: [''],
    registrationPaid: '',
    submenu: [  
      {
        path: '/founder/waters/all-products',
        title: 'MENUITEMS.PRODUCTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/waters/all-orders',
        title: 'MENUITEMS.ORDERS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },  
      {
        path: '/founder/waters/all-productMovements',
        title: 'MENUITEMS.PRODUCTS-MOVEMENT.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.STOCK-MANAGEMENT.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'layers',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:['Founder', "Direction"],
    role: ['Founder', 'Principale', 'Rector', 'assistant'],
    scholar_level: [''],
    permissions: [''],
    registrationPaid: '',
    submenu: [
      {
        path: '/founder/accountings/all-suppliers',
        title: 'MENUITEMS.SUPPLIERS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'suppliers fournisseurs partners partenaires ',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/stocks/all-articles',
        title: 'MENUITEMS.ARTICLES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/stocks/all-supplyDemands',
        title: 'MENUITEMS.SUPPLY-DEMANDS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/stocks/all-vouchers',
        title: 'MENUITEMS.PURCHASES-ORDER.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/stocks/all-articleMovements',
        title: 'MENUITEMS.ARTICLES-MOVEMENT.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/stocks/all-productMovements',
        title: 'MENUITEMS.PRODUCTS-MOVEMENT.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
  

  {
    path: '',
    title: 'MENUITEMS.ACCOUNTING.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'monetization_on',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:['Founder', "Direction"],
    role: ['Founder', 'Principale', 'Rector', 'assistant'],
    scholar_level: [''],
    permissions: [''],
    registrationPaid: '',
    submenu: [
      {
        path: '/founder/accountings/all-cashIns',
        title: 'MENUITEMS.CASH-IN.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'paiements transactions  payments pensions ',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/accountings/all-disbursements',
        title: 'MENUITEMS.EXPENSES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'depenses dépenses expenses',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      },
      /* {
        path: '/founder/transactions/add-stat',
        title: 'MENUITEMS.STAT.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'trésoreries  tresoreries treasuries treasury',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [''],
        submenu: [],
        registrationPaid: '',
      }, */
    ],
  },

  // Assessment 
  
/*  {
    path: '',
    title: 'MENUITEMS.RH.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'layers',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:['Founder', "Direction"],
    role: ['Founder', 'Principale', 'Rector', 'assistant'],
    scholar_level: [''],
    permissions: ['stf-2'],
    registrationPaid: '',
    submenu: [
      {
        path: '/founder/human-resources/all-salaryAdvances',
        title: 'MENUITEMS.SALARY-ADVANCES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['stf-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/human-resources/all-warnings',
        title: 'MENUITEMS.WARNINGS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['stf-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/human-resources/all-holidays',
        title: 'MENUITEMS.CONGES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['stf-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/human-resources/all-contracts',
        title: 'MENUITEMS.CONTRATS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['stf-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/human-resources/all-notes-frais',
        title: 'MENUITEMS.NOTE-FRAIS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['stf-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/human-resources/all-permissions',
        title: 'MENUITEMS.PERMISSIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'sequences',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['stf-2'],
        submenu: [],
        registrationPaid: '',
      }, 
      {
        path: '/founder/disciplines/all-presenceStaffs',
        title: 'MENUITEMS.PRESENCESTAFFS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'présences présences attendance',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['prS-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/disciplines/all-teacherObservations',
        title: 'MENUITEMS.OBSERVATIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'observations comments remarks',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['req-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/disciplines/all-requests',
        title: 'MENUITEMS.REQUESTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'requests demandes requêtes',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['req-2'],
        submenu: [],
        registrationPaid: '',
      }, 
      {
        path: '/founder/human-resources/all-salaryDeductions',
        title: 'MENUITEMS.PAYROLL_DEDUCTIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['stf-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/founder/human-resources/all-sanctions',
        title: 'MENUITEMS.SANCTIONS-BLAME.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'sanctions penalties',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: ['stf-2'],
        submenu: [],
        registrationPaid: '',
      },
    ],
  }, */

  // Comptabilité
  

  /* {
    path: '',
    title: 'MENUITEMS.OMS.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'monetization_on',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
typeRole:['Founder', "Direction"],
    role: ['Founder', 'Principale', 'Rector', 'assistant'],
    permissions: ['pom-2', 'fom-2', 'rom-2'],
    scholar_level: [''],
    registrationPaid: '',
    submenu: [
      {
        path: '/founder/oms/main',
        title: 'MENUITEMS.DASHBOARD.TEXT',
        iconType: 'material-icons-two-tone',
        icon: 'space_dashboard',
        class: '',
        groupTitle: false,
        badge: 'orange money om',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: ['Founder', 'Principale', 'Rector'],
        scholar_level: [''],
        submenu: [],
        permissions: ['pom-2', 'fom-2', 'rom-2'],
        registrationPaid: '',
      },
      {
        path: '/founder/oms/all-retraits',
        title: 'MENUITEMS.RETRAITS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'orange money om retraits withdrawals',
        badgeClass: '',
typeRole:['Founder', "Direction"],
        role: [''],
        scholar_level: [''],
        permissions: [ 'rom-2'],
        submenu: [],
        registrationPaid: '',
      },
    ],
  }, */
  
 
  // Staff Modules 
  {
    path: '/staff/dashboard/main',
    title: 'MENUITEMS.DASHBOARD.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'space_dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:[ "Staffs"],
    role: [''],
    permissions: ['eve-2'],
    scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
    submenu: [],
    registrationPaid: '',
  },


  // structure primaire et nursery
  {
    path: '',
    title: 'MENUITEMS.STRUCTURE.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'school',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:[ "Staffs"],
    role: [''],
    permissions: ['cyc-2','niv-2','cla-2','fil-2','opl-2'],
    scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
    registrationPaid: '',
    submenu: [
      {
        path: '/staff/structures/all-cycles',
        title: 'MENUITEMS.PEDAGOGY.LIST.CYCLES',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: ' cycles ',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['cyc-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/structures/all-streams',
        title: 'MENUITEMS.PEDAGOGY.LIST.STREAMS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'filieres filières sectors streams',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['University'],
        permissions: ['fil-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/structures/all-levels',
        title: 'MENUITEMS.PEDAGOGY.LIST.LEVELS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'levels niveaux',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['niv-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/structures/all-optionlevels',
        title: 'MENUITEMS.PEDAGOGY.LIST.OPTIONLEVELS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'option de niveau series ',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Secondary'],
        permissions: ['opl-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/structures/all-optionlevels',
        title: 'MENUITEMS.PEDAGOGY.LIST.SPECIALTIES',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'specialités specialites',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['University'],
        permissions: ['opl-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/structures/all-classrooms',
        title: 'MENUITEMS.PEDAGOGY.LIST.CLASSROOMS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'classes classsroom',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['cla-2'],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
  
  {
    path: '',
    title: 'MENUITEMS.ORGANISATION.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'person',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:[ "Staffs"],
    role: [''],
    scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
    permissions: ['stf-2', 'tea-2', 'std-2', 'eve-2', 'tac-2'],
    registrationPaid: '',
    submenu: [
      {
        path: '/staff/organisations/all-staffs',
        title: 'MENUITEMS.ORGANISATION.LIST.STAFFS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'personnels administratifs administrative staff',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        permissions: ['stf-2'],
        registrationPaid: '',
      },
      {
        path: '/staff/organisations/all-teachers',
        title: 'MENUITEMS.ORGANISATION.LIST.TEACHERS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'teachers enseignants',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        permissions: ['tea-2'],
        registrationPaid: '',
      },
      /* {
        path: '/staff/preInscriptions/all-preInscriptions',
        title: 'MENUITEMS.ORGANISATION.LIST.PREINSCRIPTIONS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University'],
        submenu: [],
        permissions: ['std-2'],
        registrationPaid: '',
      }, */
      {
        path: '/staff/organisations/all-students',
        title: 'MENUITEMS.ORGANISATION.LIST.STUDENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'élèves eleves students',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level:['Primary', 'Nursery', 'Secondary'],
        permissions: ['std-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/organisations/all-students',
        title: 'MENUITEMS.ORGANISATION.LIST.STUDENTS-U',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'etudiants étudiants students',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['University', 'CF'],
        permissions: ['std-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/organisations/all-parents',
        title: 'MENUITEMS.ORGANISATION.LIST.PARENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'parents',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary'],
        permissions: ['par-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/organisations/all-events',
        title: 'MENUITEMS.ORGANISATION.LIST.EVENTS',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'événements evenements events',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level:['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        registrationPaid: '',
        permissions: ['eve-2']
      },
      {
        path: '/staff/organisations/all-tasks',
        title: 'MENUITEMS.TASKS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'taches tâches tasks',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        registrationPaid: '',
        permissions: ['tac-2']
      },
      {
        path: '/staff/organisations/all-sms',
        title: 'MENUITEMS.SMS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'sms',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        registrationPaid: '',
        permissions: ['sms-2']
      },
      {
        path: '/staff/organisations/all-dailyReports',
        title: 'MENUITEMS.DAILY-REPORTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'daily reports rapports journaliers',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        registrationPaid: '',
        permissions: ['rpj-2']
      },
      
      {
        path: '/staff/organisations/all-suggestions',
        title: 'MENUITEMS.SUGGESTIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'suggestions avis suggestions',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        registrationPaid: '',
        permissions: ['rpj-2']
      }, 
      {
        path: '/staff/organisations/all-litiges',
        title: 'MENUITEMS.LITIGES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'litiges avis litiges',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        registrationPaid: '',
        permissions: ['rpj-2']
      },
      {
        path: '/staff/organisations/all-meetingReports',
        title: 'MENUITEMS.MEETING-REPORTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'meeting rapport de reunion ',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        registrationPaid: '',
        permissions: ['rpj-2']
      },
      {
        path: '/staff/organisations/all-memos',
        title: 'MENUITEMS.MEMOS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'memos notes de service ',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        registrationPaid: '',
        permissions: ['rpj-2']
      },
    ],
  },

  {
    path: '',
    title: 'MENUITEMS.ACCOUNTING.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'monetization_on',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:[ "Staffs"],
    role: [''],
    scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
    permissions: ['brs-2','pen-2','tra-2','fee-2','inl-2','trs-2','fou-2','dep-2'],
    registrationPaid: '',
    submenu: [
      
      {
        path: '/staff/accountings/all-budgets',
        title: 'MENUITEMS.BUDGETS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'depenses dépenses expenses',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['bud-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/accountings/all-bourses',
        title: 'MENUITEMS.BOURSES.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: ' scholarships bourses réductions remises discounts',
        badgeClass: '',
        typeRole:[],
        role: [],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['brs-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/accountings/all-pensions',
        title: 'MENUITEMS.PENSIONS.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'pensions boarding ',
        badgeClass: '',
        typeRole:[],
        role: [],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['pen-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/accountings/all-tranches',
        title: 'MENUITEMS.TRANCHES.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'tranches slices installments',
        badgeClass: '',
        typeRole:[],
        role: [],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['tra-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/accountings/all-fees',
        title: 'MENUITEMS.FEES.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'fees frais annexes',
        badgeClass: '',
        typeRole:[],
        role: [],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['fee-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/transactions/add-insolvent',
        title: 'MENUITEMS.INSOLVENTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'insolvents insolvables',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['inl-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/transactions/all-fees',
        title: 'MENUITEMS.TRANSACTIONS-FEES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'paiements transactions  payments fees',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['trs-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/transactions/all-transactions',
        title: 'MENUITEMS.TRANSACTIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'paiements transactions  payments pensions ',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['trs-2'],
        submenu: [],
        registrationPaid: '',
      }, 
      {
        path: '/staff/transactions/add-stat',
        title: 'MENUITEMS.STAT.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'trésoreries  tresoreries treasuries treasury',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['sta-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/accountings/all-cashins',
        title: 'MENUITEMS.CASHINS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'depenses dépenses expenses',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['aur-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/accountings/all-invoices',
        title: 'MENUITEMS.EXPENSES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'depenses dépenses expenses',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['dep-2'],
        submenu: [],
        registrationPaid: '',
      },
      
      {
        path: '/staff/accountings/all-moratoriums',
        title: 'MENUITEMS.MORATORIUMS.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: ' moratoriums moratoires  ',
        badgeClass: '',
        typeRole:[],
        role: [],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['trs-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/accountings/all-bonuses',
        title: 'MENUITEMS.BONUSES.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: ' scholarships bonuses réductions remises discounts primes',
        badgeClass: '',
        typeRole:[],
        role: [],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['pri-2'],
        submenu: [],
        registrationPaid: '',
      }, 
      {
        path: '/staff/transactions/all-scanReceipts',
        title: 'MENUITEMS.SCAN-RECEIPTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'reçu recu scan receipt ',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['trs-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/accountings/all-transports',
        title: 'MENUITEMS.TRANSPORTS.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: ' transports transport',
        badgeClass: '',
        typeRole:[],
        role: [],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['trs-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/accountings/all-transportsUsers',
        title: 'MENUITEMS.TRANSPORTS-USERS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: ' transports transport',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['trs-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/accountings/all-paymentTransportsUsers',
        title: 'MENUITEMS.PAYMENTS-TRANSPORTS-USERS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'paiememnts payments transports transport',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['trs-2'],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },


  {
    path: '',
    title: 'MENUITEMS.DISCIPLINE.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'person',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:[ "Staffs"],
    role: [''],
    scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
    permissions: ['req-2', 'prS-2', 'pre-2'],
    registrationPaid: '',
    submenu: [
      {
        path: '/staff/disciplines/all-schoolDelays',
        title: 'MENUITEMS.SCHOOL-DELAYS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'absences',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['abs-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/disciplines/all-absences',
        title: 'MENUITEMS.ABSENCES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'absences',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['abs-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/disciplines/all-sanctions',
        title: 'MENUITEMS.SANCTIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'sanctions penalties',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['san-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/disciplines/all-teacherObservations',
        title: 'MENUITEMS.OBSERVATIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'observations comments remarks',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['obs-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/disciplines/all-requests',
        title: 'MENUITEMS.REQUESTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'requests demandes requêtes',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['req-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/disciplines/all-presenceStaffs',
        title: 'MENUITEMS.PRESENCESTAFFS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'présences présences attendance',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['prS-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/disciplines/all-presenceteachers',
        title: 'MENUITEMS.PRESENCETEACHERS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'présences présences attendance',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['pre-2'],
        submenu: [],
        registrationPaid: '',
      }
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.PEDAGOGY.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'layers',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:[ "Staffs"],
    role: [''],
    permissions: ['mat-2','grp-2','cou-2','prg-2'],
    scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
    registrationPaid: '',
    submenu: [
      {
        path: '/staff/pedogogies/all-matters',
        title: 'MENUITEMS.MATTERS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'matters matières',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['mat-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/pedogogies/all-matterGroups',
        title: 'MENUITEMS.MATTER-GROUPS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'groups groupes matters matières',
        badgeClass: '',
        typeRole:[],
        role: [''],
        permissions: ['grp-2'],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/pedogogies/all-courses',
        title: 'MENUITEMS.COURSES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'courses cours emploi de temps timetable schedule',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['cou-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/pedogogies/schedule',
        title: 'MENUITEMS.SCHEDULE.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'courses cours emploi de temps timetable schedule',
        badgeClass: '',
        typeRole:[],
        role: [],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['cou-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/pedogogies/all-summaries',
        title: 'MENUITEMS.SUMMARIES.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'resumé de cours summaries',
        badgeClass: '',
        typeRole:[],
        role: [],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['rsm-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/pedogogies/all-homeworks',
        title: 'MENUITEMS.HOMEWORKS.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'devoir homework ',
        badgeClass: '',
        typeRole:[],
        role: [],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['dvr-2', 'hom-2'],
        submenu: [],
        registrationPaid: '',
      },
      
      {
        path: '/staff/pedogogies/all-progressions',
        title: 'MENUITEMS.PROGRESSIONS.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'progressions cahier de texte textbook chapters lessons chapitres leçons lecons',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        submenu: [],
        permissions: ['prg-2'],
        registrationPaid: '',
      },
      {
        path: '/staff/pedogogies/all-schoolSupplys',
        title: 'MENUITEMS.SCHOOL-SUPPLY.TEXT',
        iconType: 'material-icons-two-tone',
        icon: 'money',
        class: '',
        groupTitle: false,
        badge: 'fournitures scolaire school supplys',
        badgeClass: '',
        typeRole:[],
        role: ['Parent','Inscription'],
        permissions: ['fns-2'],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        submenu: [],
        registrationPaid: [true, null],
      },
    ],
  },

  // Assessment 
  {
    path: '',
    title: 'MENUITEMS.ASSESSMENTS.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'layers',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:[ "Staffs"],
    role: [''],
    scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
    permissions: ['tri-2', 'séq-2', 'tev-2', 'eva-2', 'not-2', 'bul-2'],
    registrationPaid: '',
    submenu: [
      {
        path: '/staff/assessmentTypes/all-trimestres',
        title: 'MENUITEMS.TRIMESTRES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'trimestres quarters trimesters',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary'],
        permissions: ['tri-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/assessmentTypes/all-sequences',
        title: 'MENUITEMS.SEQUENCES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'sequences',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary',],
        permissions: ['séq-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/assessmentTypes/all-trimestres',
        title: 'MENUITEMS.SEMESTRE.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['University', 'CF'],
        permissions: ['tri-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/assessmentTypes/all-sequences',
        title: 'MENUITEMS.CC.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'cc',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['University', 'CF'],
        permissions: ['séq-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/assessmentTypes/all-typeEvaluations',
        title: 'MENUITEMS.ASSESSMENTS-TYPES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'sequences',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery'],
        permissions: ['tev-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/assessmentTypes/all-assessments',
        title: 'MENUITEMS.ASSESSMENTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'evaluations évaluations assessments',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['eva-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/assessmentTypes/all-questionnaires',
        title: 'MENUITEMS.QUESTIONNAIRES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'questionnnaires questions',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['que-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/assessmentTypes/all-responses',
        title: 'MENUITEMS.RESPONSES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'questionnnaires questions responses answer reply',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['rep-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/assessmentTypes/all-examinationPapers',
        title: 'MENUITEMS.EXAMINATION-PAPERS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'questionnnaires questions responses answer reply',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['eva-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/ratings/all-ratings',
        title: 'MENUITEMS.RATINGS.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'ratings notes marks mks',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['not-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/bulletins/add-bulletin',
        title: 'MENUITEMS.REPORT-CARD.TEXT',
        iconType: 'material-icons-two-tone',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'report card bulletin rélévé de notes transcript of records',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['bul-2'],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.STOCK-MANAGEMENT.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'layers',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:[ "Staffs"],
    role: [''],
    scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
    permissions: ['fou-2', 'art-2', 'dap-2', 'bdc-2', 'moa-2'],
    registrationPaid: '',
    submenu: [ 
      {
        path: '/staff/stocks/all-suppliers',
        title: 'MENUITEMS.SUPPLIERS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'suppliers fournisseurs partners partenaires ',
        badgeClass: '',
    typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['fou-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/stocks/all-articles',
        title: 'MENUITEMS.ARTICLES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
    typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['art-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/stocks/all-supplyDemands',
        title: 'MENUITEMS.SUPPLY-DEMANDS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
    typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['dap-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/stocks/all-vouchers',
        title: 'MENUITEMS.PURCHASES-ORDER.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
    typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['bdc-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/stocks/all-articleMovements',
        title: 'MENUITEMS.ARTICLES-MOVEMENT.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
    typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['moa-2'],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.RH.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'layers',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:[ "Staffs"],
    role: [''],
    scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
    permissions: ['ass-2', 'ave-2', 'cgs-2' ,'con-2' , 'ndf-2', 'per-2', 'rss-2', 'san-2'],
    registrationPaid: '',
    submenu: [
      {
        path: '/staff/human-resources/all-salaryAdvances',
        title: 'MENUITEMS.SALARY-ADVANCES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['ass-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/human-resources/all-warnings',
        title: 'MENUITEMS.WARNINGS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['ave-2'],
        submenu: [],
        registrationPaid: '',
      }, 
      {
        path: '/staff/human-resources/all-explanationRequests',
        title: 'MENUITEMS.EXPLANATION-REQUESTS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'explanation requests demande d explications',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['ave-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/human-resources/all-holidays',
        title: 'MENUITEMS.CONGES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['cgs-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/human-resources/all-contracts',
        title: 'MENUITEMS.CONTRATS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['con-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/human-resources/all-notes-frais',
        title: 'MENUITEMS.NOTE-FRAIS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'trimestres quarters trimesters',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['ndf-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/human-resources/all-permissions',
        title: 'MENUITEMS.PERMISSIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'sequences',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['per-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/human-resources/all-salaryDeductions',
        title: 'MENUITEMS.PAYROLL_DEDUCTIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'semestres half-years',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['rss-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/human-resources/all-sanctions',
        title: 'MENUITEMS.SANCTIONS-BLAME.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'sanctions penalties',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary','University', 'CF'],
        permissions: ['san-2'],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
  {
    path: '',
    title: 'MENUITEMS.OMS.TEXT',
    iconType: 'material-icons-two-tone',
    icon: 'monetization_on',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    typeRole:[ "Staffs"],
    role: [''],
    permissions: ['pom-2', 'fom-2', 'rom-2'],
    scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
    registrationPaid: '',
    submenu: [
      {
        path: '/staff/oms/main',
        title: 'MENUITEMS.DASHBOARD.TEXT',
        iconType: 'material-icons-two-tone',
        icon: 'space_dashboard',
        class: '',
        groupTitle: false,
        badge: 'orange money om',
        badgeClass: '',
        typeRole:[],
        role: ['Founder', 'Principale', 'Rector'],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        submenu: [],
        permissions: ['pom-2', 'fom-2', 'rom-2'],
        registrationPaid: '',
      },
      /* {
        path: '/founder/oms/all-transactions',
        title: 'MENUITEMS.TRANSACTIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'paiements transactions  payments pensions ',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['trs-2'],
        submenu: [],
        registrationPaid: '',
      }, */
      {
        path: '/staff/oms/all-oms',
        title: 'MENUITEMS.PENSIONS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'orange money om',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['pom-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/oms/all-feeOs',
        title: 'MENUITEMS.FEES.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'orange money om',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: ['fom-2'],
        submenu: [],
        registrationPaid: '',
      },
      {
        path: '/staff/oms/all-retraits',
        title: 'MENUITEMS.RETRAITS.TEXT',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: 'orange money om retraits withdrawals',
        badgeClass: '',
        typeRole:[],
        role: [''],
        scholar_level: ['Primary', 'Nursery', 'Secondary', 'University', 'CF'],
        permissions: [ 'rom-2'],
        submenu: [],
        registrationPaid: '',
      },
    ],
  },
 
];
